language: generic
sudo: required

services:
    - docker

before_install:
    - docker build -t someshprajapati/docker-travis-ci-integration -f Dockerfile.dev .

script:
    - docker run -e CI=true someshprajapati/docker-travis-ci-integration npm run test -- --coverage